<?php
// All 114 Surahs with SEO slugs
$surahs = [
  1=>['ar'=>'الفاتحة','en'=>'Al-Fatiha','slug'=>'al-fatiha','ayahs'=>7,'type'=>'Makkiyah','meaning'=>'The Opening','benefit'=>'Read in every prayer. Most repeated surah in the Quran.'],
  2=>['ar'=>'البقرة','en'=>'Al-Baqarah','slug'=>'al-baqarah','ayahs'=>286,'type'=>'Madaniyah','meaning'=>'The Cow','benefit'=>'Longest surah. Last two ayahs protect from all evil at night.'],
  3=>['ar'=>'آل عمران','en'=>'Al-Imran','slug'=>'al-imran','ayahs'=>200,'type'=>'Madaniyah','meaning'=>'Family of Imran','benefit'=>'Two flowers of the Quran — Al-Baqarah and Al-Imran will intercede.'],
  4=>['ar'=>'النساء','en'=>'An-Nisa','slug'=>'an-nisa','ayahs'=>176,'type'=>'Madaniyah','meaning'=>'The Women','benefit'=>'Contains laws of inheritance and family rights in Islam.'],
  5=>['ar'=>'المائدة','en'=>'Al-Maidah','slug'=>'al-maidah','ayahs'=>120,'type'=>'Madaniyah','meaning'=>'The Table Spread','benefit'=>'Last major surah revealed. Contains perfection of religion verse.'],
  6=>['ar'=>'الأنعام','en'=>'Al-Anam','slug'=>'al-anam','ayahs'=>165,'type'=>'Makkiyah','meaning'=>'The Cattle','benefit'=>'70,000 angels descended when this surah was revealed.'],
  7=>['ar'=>'الأعراف','en'=>'Al-Araf','slug'=>'al-araf','ayahs'=>206,'type'=>'Makkiyah','meaning'=>'The Heights','benefit'=>'Contains story of Adam, Noah, Hud, Salih, Lot and Shuaib.'],
  8=>['ar'=>'الأنفال','en'=>'Al-Anfal','slug'=>'al-anfal','ayahs'=>75,'type'=>'Madaniyah','meaning'=>'The Spoils of War','benefit'=>'Revealed after Battle of Badr. Contains laws of Jihad.'],
  9=>['ar'=>'التوبة','en'=>'At-Tawbah','slug'=>'at-tawbah','ayahs'=>129,'type'=>'Madaniyah','meaning'=>'The Repentance','benefit'=>'Only surah without Bismillah. Contains Ayat Al-Kursi equivalent.'],
  10=>['ar'=>'يونس','en'=>'Yunus','slug'=>'yunus','ayahs'=>109,'type'=>'Makkiyah','meaning'=>'Jonah','benefit'=>'Contains story of Prophet Yunus and the whale.'],
  11=>['ar'=>'هود','en'=>'Hud','slug'=>'hud','ayahs'=>123,'type'=>'Makkiyah','meaning'=>'Hud','benefit'=>'Prophet said this surah and its sisters made him old.'],
  12=>['ar'=>'يوسف','en'=>'Yusuf','slug'=>'yusuf','ayahs'=>111,'type'=>'Makkiyah','meaning'=>'Joseph','benefit'=>'Most beautiful story in the Quran. Complete story of Prophet Yusuf.'],
  13=>['ar'=>'الرعد','en'=>'Ar-Rad','slug'=>'ar-rad','ayahs'=>43,'type'=>'Madaniyah','meaning'=>'The Thunder','benefit'=>'He who recites it will be given ten times the number of those who believed and disbelieved in prophets.'],
  14=>['ar'=>'إبراهيم','en'=>'Ibrahim','slug'=>'ibrahim','ayahs'=>52,'type'=>'Makkiyah','meaning'=>'Abraham','benefit'=>'Contains Dua of Ibrahim for Makkah and his family.'],
  15=>['ar'=>'الحجر','en'=>'Al-Hijr','slug'=>'al-hijr','ayahs'=>99,'type'=>'Makkiyah','meaning'=>'The Rocky Tract','benefit'=>'Contains promise of Allah to preserve the Quran forever.'],
  16=>['ar'=>'النحل','en'=>'An-Nahl','slug'=>'an-nahl','ayahs'=>128,'type'=>'Makkiyah','meaning'=>'The Bee','benefit'=>'Called Surah An-Niam (Blessings). Contains 16:97 promise of good life.'],
  17=>['ar'=>'الإسراء','en'=>'Al-Isra','slug'=>'al-isra','ayahs'=>111,'type'=>'Makkiyah','meaning'=>'The Night Journey','benefit'=>'Contains the Night Journey to Jerusalem and ascent to heavens.'],
  18=>['ar'=>'الكهف','en'=>'Al-Kahf','slug'=>'al-kahf','ayahs'=>110,'type'=>'Makkiyah','meaning'=>'The Cave','benefit'=>'Read every Friday. First 10 ayahs protect from Dajjal. Light between two Fridays.'],
  19=>['ar'=>'مريم','en'=>'Maryam','slug'=>'maryam','ayahs'=>98,'type'=>'Makkiyah','meaning'=>'Mary','benefit'=>'Contains birth of Isa (Jesus). Negus of Abyssinia wept when he heard it.'],
  20=>['ar'=>'طه','en'=>'Taha','slug'=>'taha','ayahs'=>135,'type'=>'Makkiyah','meaning'=>'Ta-Ha','benefit'=>'Umar ibn Al-Khattab accepted Islam after hearing this surah.'],
  21=>['ar'=>'الأنبياء','en'=>'Al-Anbiya','slug'=>'al-anbiya','ayahs'=>112,'type'=>'Makkiyah','meaning'=>'The Prophets','benefit'=>'Mentions 17 prophets. Contains story of Prophet Ibrahim in the fire.'],
  22=>['ar'=>'الحج','en'=>'Al-Hajj','slug'=>'al-hajj','ayahs'=>78,'type'=>'Madaniyah','meaning'=>'The Pilgrimage','benefit'=>'Contains two verses of prostration. Describes Day of Judgement vividly.'],
  23=>['ar'=>'المؤمنون','en'=>'Al-Muminun','slug'=>'al-muminun','ayahs'=>118,'type'=>'Makkiyah','meaning'=>'The Believers','benefit'=>'First 10 ayahs describe successful believers. Prophet wept during recitation.'],
  24=>['ar'=>'النور','en'=>'An-Nur','slug'=>'an-nur','ayahs'=>64,'type'=>'Madaniyah','meaning'=>'The Light','benefit'=>'Contains Ayat An-Nur — the Light verse. Laws of modesty and chastity.'],
  25=>['ar'=>'الفرقان','en'=>'Al-Furqan','slug'=>'al-furqan','ayahs'=>77,'type'=>'Makkiyah','meaning'=>'The Criterion','benefit'=>'Describes servants of Rahman. Night prayers described beautifully.'],
  26=>['ar'=>'الشعراء','en'=>'Ash-Shuara','slug'=>'ash-shuara','ayahs'=>227,'type'=>'Makkiyah','meaning'=>'The Poets','benefit'=>'Contains stories of Musa, Ibrahim, Nuh, Hud, Salih, Lut and Shuaib.'],
  27=>['ar'=>'النمل','en'=>'An-Naml','slug'=>'an-naml','ayahs'=>93,'type'=>'Makkiyah','meaning'=>'The Ant','benefit'=>'Contains story of Sulaiman and Queen of Sheba. Bismillah mentioned twice.'],
  28=>['ar'=>'القصص','en'=>'Al-Qasas','slug'=>'al-qasas','ayahs'=>88,'type'=>'Makkiyah','meaning'=>'The Stories','benefit'=>'Most detailed account of Prophet Musa\'s life from birth to prophethood.'],
  29=>['ar'=>'العنكبوت','en'=>'Al-Ankabut','slug'=>'al-ankabut','ayahs'=>69,'type'=>'Makkiyah','meaning'=>'The Spider','benefit'=>'Those who strive for Allah — He will guide them to His paths.'],
  30=>['ar'=>'الروم','en'=>'Ar-Rum','slug'=>'ar-rum','ayahs'=>60,'type'=>'Makkiyah','meaning'=>'The Romans','benefit'=>'Predicted Roman victory over Persians — fulfilled exactly as prophesied.'],
  31=>['ar'=>'لقمان','en'=>'Luqman','slug'=>'luqman','ayahs'=>34,'type'=>'Makkiyah','meaning'=>'Luqman','benefit'=>'Contains wisdom of Luqman to his son. Perfect parenting advice from Quran.'],
  32=>['ar'=>'السجدة','en'=>'As-Sajdah','slug'=>'as-sajdah','ayahs'=>30,'type'=>'Makkiyah','meaning'=>'The Prostration','benefit'=>'Prophet ﷺ read this every Friday Fajr with Surah Al-Insan.'],
  33=>['ar'=>'الأحزاب','en'=>'Al-Ahzab','slug'=>'al-ahzab','ayahs'=>73,'type'=>'Madaniyah','meaning'=>'The Combined Forces','benefit'=>'Contains verse of Salawat on Prophet. Most blessings earned through this.'],
  34=>['ar'=>'سبأ','en'=>'Saba','slug'=>'saba','ayahs'=>54,'type'=>'Makkiyah','meaning'=>'Sheba','benefit'=>'Contains story of Prophet Dawud and Sulaiman and their blessings.'],
  35=>['ar'=>'فاطر','en'=>'Fatir','slug'=>'fatir','ayahs'=>45,'type'=>'Makkiyah','meaning'=>'Originator','benefit'=>'Angels described as having 2, 3 and 4 wings. Allah is Creator of everything.'],
  36=>['ar'=>'يس','en'=>'Ya-Sin','slug'=>'ya-sin','ayahs'=>83,'type'=>'Makkiyah','meaning'=>'Ya-Sin','benefit'=>'Heart of the Quran. Read for the dying. Every thing has a heart and the heart of the Quran is Ya-Sin.'],
  37=>['ar'=>'الصافات','en'=>'As-Saffat','slug'=>'as-saffat','ayahs'=>182,'type'=>'Makkiyah','meaning'=>'Those Drawn Up in Ranks','benefit'=>'Angels described standing in rows before Allah. Story of Ibrahim and his son.'],
  38=>['ar'=>'ص','en'=>'Sad','slug'=>'sad','ayahs'=>88,'type'=>'Makkiyah','meaning'=>'Sad','benefit'=>'Contains story of Prophet Dawud\'s repentance. Verse of prostration in it.'],
  39=>['ar'=>'الزمر','en'=>'Az-Zumar','slug'=>'az-zumar','ayahs'=>75,'type'=>'Makkiyah','meaning'=>'The Groups','benefit'=>'Contains most hopeful verse in Quran — Allah forgives all sins.'],
  40=>['ar'=>'غافر','en'=>'Ghafir','slug'=>'ghafir','ayahs'=>85,'type'=>'Makkiyah','meaning'=>'The Forgiver','benefit'=>'First of the Hawamim surahs. Believer of Pharaoh\'s family defends Musa.'],
  41=>['ar'=>'فصلت','en'=>'Fussilat','slug'=>'fussilat','ayahs'=>54,'type'=>'Makkiyah','meaning'=>'Explained in Detail','benefit'=>'Earth and sky created in 6 days. Angels descend on believers at death.'],
  42=>['ar'=>'الشورى','en'=>'Ash-Shura','slug'=>'ash-shura','ayahs'=>53,'type'=>'Makkiyah','meaning'=>'The Consultation','benefit'=>'Consultation is from the way of believers. Beautiful description of revelation.'],
  43=>['ar'=>'الزخرف','en'=>'Az-Zukhruf','slug'=>'az-zukhruf','ayahs'=>89,'type'=>'Makkiyah','meaning'=>'The Gold Adornments','benefit'=>'Contains hadith of riding supplication. Story of Ibrahim questioning his people.'],
  44=>['ar'=>'الدخان','en'=>'Ad-Dukhan','slug'=>'ad-dukhan','ayahs'=>59,'type'=>'Makkiyah','meaning'=>'The Smoke','benefit'=>'Prophet ﷺ recited this every Friday night. 70,000 angels seek forgiveness for reciter.'],
  45=>['ar'=>'الجاثية','en'=>'Al-Jathiyah','slug'=>'al-jathiyah','ayahs'=>37,'type'=>'Makkiyah','meaning'=>'The Crouching','benefit'=>'Signs in creation pointed to Allah\'s existence. All will kneel on Day of Judgement.'],
  46=>['ar'=>'الأحقاف','en'=>'Al-Ahqaf','slug'=>'al-ahqaf','ayahs'=>35,'type'=>'Makkiyah','meaning'=>'The Wind-Curved Sandhills','benefit'=>'Jinn listened to Quran recitation here and believed. Contains dua for parents.'],
  47=>['ar'=>'محمد','en'=>'Muhammad','slug'=>'muhammad','ayahs'=>38,'type'=>'Madaniyah','meaning'=>'Muhammad','benefit'=>'Named after the Prophet ﷺ. Contains description of paradise rivers.'],
  48=>['ar'=>'الفتح','en'=>'Al-Fath','slug'=>'al-fath','ayahs'=>29,'type'=>'Madaniyah','meaning'=>'The Victory','benefit'=>'Dearer to Prophet than everything under the sun. Revealed after Hudaybiyyah.'],
  49=>['ar'=>'الحجرات','en'=>'Al-Hujurat','slug'=>'al-hujurat','ayahs'=>18,'type'=>'Madaniyah','meaning'=>'The Rooms','benefit'=>'Islamic ethics and social conduct. Brotherhood of believers emphasized.'],
  50=>['ar'=>'ق','en'=>'Qaf','slug'=>'qaf','ayahs'=>45,'type'=>'Makkiyah','meaning'=>'Qaf','benefit'=>'Prophet ﷺ recited this in Friday Khutbah. Death and resurrection described.'],
  51=>['ar'=>'الذاريات','en'=>'Adh-Dhariyat','slug'=>'adh-dhariyat','ayahs'=>60,'type'=>'Makkiyah','meaning'=>'The Winnowing Winds','benefit'=>'I have not created jinn and humans except to worship Me — verse 56.'],
  52=>['ar'=>'الطور','en'=>'At-Tur','slug'=>'at-tur','ayahs'=>49,'type'=>'Makkiyah','meaning'=>'The Mount','benefit'=>'Umar ibn Al-Khattab wept severely when he heard this surah.'],
  53=>['ar'=>'النجم','en'=>'An-Najm','slug'=>'an-najm','ayahs'=>62,'type'=>'Makkiyah','meaning'=>'The Star','benefit'=>'First surah with prostration. Even polytheists prostrated when they heard it.'],
  54=>['ar'=>'القمر','en'=>'Al-Qamar','slug'=>'al-qamar','ayahs'=>55,'type'=>'Makkiyah','meaning'=>'The Moon','benefit'=>'Describes splitting of the moon miracle. Every story ends with easy reminder.'],
  55=>['ar'=>'الرحمن','en'=>'Ar-Rahman','slug'=>'ar-rahman','ayahs'=>78,'type'=>'Madaniyah','meaning'=>'The Most Merciful','benefit'=>'Bride of the Quran. Which favours of your Lord will you deny? repeated 31 times.'],
  56=>['ar'=>'الواقعة','en'=>'Al-Waqiah','slug'=>'al-waqiah','ayahs'=>96,'type'=>'Makkiyah','meaning'=>'The Inevitable','benefit'=>'Whoever reads it every night will never be afflicted by poverty.'],
  57=>['ar'=>'الحديد','en'=>'Al-Hadid','slug'=>'al-hadid','ayahs'=>29,'type'=>'Madaniyah','meaning'=>'The Iron','benefit'=>'He is Al-Awwal and Al-Akhir — beautiful names of Allah in this surah.'],
  58=>['ar'=>'المجادلة','en'=>'Al-Mujadila','slug'=>'al-mujadila','ayahs'=>22,'type'=>'Madaniyah','meaning'=>'The Pleading Woman','benefit'=>'Allah heard the woman who argued with Prophet. He hears all complaints.'],
  59=>['ar'=>'الحشر','en'=>'Al-Hashr','slug'=>'al-hashr','ayahs'=>24,'type'=>'Madaniyah','meaning'=>'The Exile','benefit'=>'Last 3 ayahs contain beautiful names of Allah. Read after Fajr and Maghrib.'],
  60=>['ar'=>'الممتحنة','en'=>'Al-Mumtahanah','slug'=>'al-mumtahanah','ayahs'=>13,'type'=>'Madaniyah','meaning'=>'She That Is To Be Examined','benefit'=>'Ibrahim\'s dua for disavowal of polytheists is a model for believers.'],
  61=>['ar'=>'الصف','en'=>'As-Saf','slug'=>'as-saf','ayahs'=>14,'type'=>'Madaniyah','meaning'=>'The Ranks','benefit'=>'Jesus prophesied coming of Prophet Ahmad (Muhammad). Fighting in ranks like building.'],
  62=>['ar'=>'الجمعة','en'=>'Al-Jumuah','slug'=>'al-jumuah','ayahs'=>11,'type'=>'Madaniyah','meaning'=>'Friday','benefit'=>'Prophet ﷺ read this surah in Friday prayer. Laws of Jumu\'ah prayer.'],
  63=>['ar'=>'المنافقون','en'=>'Al-Munafiqun','slug'=>'al-munafiqun','ayahs'=>11,'type'=>'Madaniyah','meaning'=>'The Hypocrites','benefit'=>'Describes hypocrisy and its signs. Warning against being distracted by wealth.'],
  64=>['ar'=>'التغابن','en'=>'At-Taghabun','slug'=>'at-taghabun','ayahs'=>18,'type'=>'Madaniyah','meaning'=>'Mutual Disillusion','benefit'=>'Day of mutual loss and gain. Your spouse and children may be your enemies.'],
  65=>['ar'=>'الطلاق','en'=>'At-Talaq','slug'=>'at-talaq','ayahs'=>12,'type'=>'Madaniyah','meaning'=>'Divorce','benefit'=>'Whoever fears Allah He will make a way out for him — beautiful promise.'],
  66=>['ar'=>'التحريم','en'=>'At-Tahrim','slug'=>'at-tahrim','ayahs'=>12,'type'=>'Madaniyah','meaning'=>'The Prohibition','benefit'=>'Guard yourselves and your families against Fire — responsibility of every believer.'],
  67=>['ar'=>'الملك','en'=>'Al-Mulk','slug'=>'al-mulk','ayahs'=>30,'type'=>'Makkiyah','meaning'=>'The Sovereignty','benefit'=>'Intercedes for its reciter until forgiven. Read every night before sleep.'],
  68=>['ar'=>'القلم','en'=>'Al-Qalam','slug'=>'al-qalam','ayahs'=>52,'type'=>'Makkiyah','meaning'=>'The Pen','benefit'=>'Second surah revealed to Prophet ﷺ. By the pen and what they write.'],
  69=>['ar'=>'الحاقة','en'=>'Al-Haqqah','slug'=>'al-haqqah','ayahs'=>52,'type'=>'Makkiyah','meaning'=>'The Reality','benefit'=>'Vivid description of Day of Judgement. Stories of Thamud and Ad who were destroyed.'],
  70=>['ar'=>'المعارج','en'=>'Al-Maarij','slug'=>'al-maarij','ayahs'=>44,'type'=>'Makkiyah','meaning'=>'The Ascending Stairways','benefit'=>'Description of Day of Judgement. Angels and Ruh ascend in a day equal to 50,000 years.'],
  71=>['ar'=>'نوح','en'=>'Nuh','slug'=>'nuh','ayahs'=>28,'type'=>'Makkiyah','meaning'=>'Noah','benefit'=>'Complete story of Prophet Nuh\'s 950 years of dawah. Dua of Nuh against disbelievers.'],
  72=>['ar'=>'الجن','en'=>'Al-Jinn','slug'=>'al-jinn','ayahs'=>28,'type'=>'Makkiyah','meaning'=>'The Jinn','benefit'=>'Jinn listened to Quran and immediately believed. We heard amazing recitation.'],
  73=>['ar'=>'المزمل','en'=>'Al-Muzzammil','slug'=>'al-muzzammil','ayahs'=>20,'type'=>'Makkiyah','meaning'=>'The Enshrouded One','benefit'=>'O you wrapped in garments — first direct address to Prophet. Night prayer commanded.'],
  74=>['ar'=>'المدثر','en'=>'Al-Muddaththir','slug'=>'al-muddaththir','ayahs'=>56,'type'=>'Makkiyah','meaning'=>'The Cloaked One','benefit'=>'Second direct revelation after Al-Alaq. O you wrapped in a cloak — arise and warn.'],
  75=>['ar'=>'القيامة','en'=>'Al-Qiyamah','slug'=>'al-qiyamah','ayahs'=>40,'type'=>'Makkiyah','meaning'=>'The Resurrection','benefit'=>'Vivid description of resurrection. Man will be witness against himself.'],
  76=>['ar'=>'الإنسان','en'=>'Al-Insan','slug'=>'al-insan','ayahs'=>31,'type'=>'Madaniyah','meaning'=>'The Human','benefit'=>'Prophet ﷺ read this on Friday Fajr with As-Sajdah. Description of paradise.'],
  77=>['ar'=>'المرسلات','en'=>'Al-Mursalat','slug'=>'al-mursalat','ayahs'=>50,'type'=>'Makkiyah','meaning'=>'The Emissaries','benefit'=>'Woe that Day to the deniers — repeated 10 times. Last surah heard by companions.'],
  78=>['ar'=>'النبأ','en'=>'An-Naba','slug'=>'an-naba','ayahs'=>40,'type'=>'Makkiyah','meaning'=>'The Announcement','benefit'=>'About what are they asking one another — the great news of resurrection.'],
  79=>['ar'=>'النازعات','en'=>'An-Naziat','slug'=>'an-naziat','ayahs'=>46,'type'=>'Makkiyah','meaning'=>'Those Who Drag Forth','benefit'=>'Angels who extract souls — those of believers gently and disbelievers harshly.'],
  80=>['ar'=>'عبس','en'=>'Abasa','slug'=>'abasa','ayahs'=>42,'type'=>'Makkiyah','meaning'=>'He Frowned','benefit'=>'Prophet ﷺ was gently corrected by Allah for frowning at a blind companion.'],
  81=>['ar'=>'التكوير','en'=>'At-Takwir','slug'=>'at-takwir','ayahs'=>29,'type'=>'Makkiyah','meaning'=>'The Overthrowing','benefit'=>'Whoever wishes to see Day of Judgement as if with his eye should read this surah.'],
  82=>['ar'=>'الانفطار','en'=>'Al-Infitar','slug'=>'al-infitar','ayahs'=>19,'type'=>'Makkiyah','meaning'=>'The Cleaving','benefit'=>'Companion to At-Takwir. O man what has deceived you about your generous Lord.'],
  83=>['ar'=>'المطففين','en'=>'Al-Mutaffifin','slug'=>'al-mutaffifin','ayahs'=>36,'type'=>'Makkiyah','meaning'=>'The Defrauding','benefit'=>'Woe to those who give less than due. Punishes cheaters in business.'],
  84=>['ar'=>'الانشقاق','en'=>'Al-Inshiqaq','slug'=>'al-inshiqaq','ayahs'=>25,'type'=>'Makkiyah','meaning'=>'The Splitting Open','benefit'=>'You are laboring toward your Lord with exertion and will meet it. Journey to Allah.'],
  85=>['ar'=>'البروج','en'=>'Al-Buruj','slug'=>'al-buruj','ayahs'=>22,'type'=>'Makkiyah','meaning'=>'The Mansions of the Stars','benefit'=>'Story of the people of the ditch. Allah avenges the believers.'],
  86=>['ar'=>'الطارق','en'=>'At-Tariq','slug'=>'at-tariq','ayahs'=>17,'type'=>'Makkiyah','meaning'=>'The Morning Star','benefit'=>'By the sky and the night visitor — the piercing star. Every soul has a guardian.'],
  87=>['ar'=>'الأعلى','en'=>'Al-Ala','slug'=>'al-ala','ayahs'=>19,'type'=>'Makkiyah','meaning'=>'The Most High','benefit'=>'Prophet ﷺ loved this surah. Read in Friday and Eid prayers with Al-Ghashiyah.'],
  88=>['ar'=>'الغاشية','en'=>'Al-Ghashiyah','slug'=>'al-ghashiyah','ayahs'=>26,'type'=>'Makkiyah','meaning'=>'The Overwhelming','benefit'=>'Read in Friday and Eid prayers. Has the news of the Overwhelming event reached you.'],
  89=>['ar'=>'الفجر','en'=>'Al-Fajr','slug'=>'al-fajr','ayahs'=>30,'type'=>'Makkiyah','meaning'=>'The Dawn','benefit'=>'O tranquil soul — return to your Lord pleased and pleasing. Beautiful ending.'],
  90=>['ar'=>'البلد','en'=>'Al-Balad','slug'=>'al-balad','ayahs'=>20,'type'=>'Makkiyah','meaning'=>'The City','benefit'=>'I swear by this city Makkah. Man was created in hardship — must strive.'],
  91=>['ar'=>'الشمس','en'=>'Ash-Shams','slug'=>'al-shams','ayahs'=>15,'type'=>'Makkiyah','meaning'=>'The Sun','benefit'=>'Whoever purifies his soul succeeds. He who corrupts it fails. Seven oaths of Allah.'],
  92=>['ar'=>'الليل','en'=>'Al-Layl','slug'=>'al-layl','ayahs'=>21,'type'=>'Makkiyah','meaning'=>'The Night','benefit'=>'Generous person who spends will be eased to ease. Miser will be eased to difficulty.'],
  93=>['ar'=>'الضحى','en'=>'Ad-Duha','slug'=>'ad-duha','ayahs'=>11,'type'=>'Makkiyah','meaning'=>'The Morning Brightness','benefit'=>'Your Lord has not forsaken you nor hated you. Comfort to Prophet and all believers.'],
  94=>['ar'=>'الشرح','en'=>'Ash-Sharh','slug'=>'ash-sharh','ayahs'=>8,'type'=>'Makkiyah','meaning'=>'The Relief','benefit'=>'With hardship comes ease — said twice for emphasis. Companion to Ad-Duha.'],
  95=>['ar'=>'التين','en'=>'At-Tin','slug'=>'at-tin','ayahs'=>8,'type'=>'Makkiyah','meaning'=>'The Fig','benefit'=>'We created man in the best form then reduced him to lowest. Unless he believes.'],
  96=>['ar'=>'العلق','en'=>'Al-Alaq','slug'=>'al-alaq','ayahs'=>19,'type'=>'Makkiyah','meaning'=>'The Clot','benefit'=>'First revealed surah. Read in the name of your Lord who created. Iqra — the command.'],
  97=>['ar'=>'القدر','en'=>'Al-Qadr','slug'=>'al-qadr','ayahs'=>5,'type'=>'Makkiyah','meaning'=>'The Power','benefit'=>'Better than 1000 months. Laylat Al-Qadr in last 10 nights of Ramadan.'],
  98=>['ar'=>'البينة','en'=>'Al-Bayyinah','slug'=>'al-bayyinah','ayahs'=>8,'type'=>'Madaniyah','meaning'=>'The Clear Proof','benefit'=>'Those who believe and do good deeds are the best of creatures. Their reward is paradise.'],
  99=>['ar'=>'الزلزلة','en'=>'Az-Zalzalah','slug'=>'az-zalzalah','ayahs'=>8,'type'=>'Madaniyah','meaning'=>'The Earthquake','benefit'=>'Equal to half the Quran. Whoever does an atom of good or evil will see it.'],
  100=>['ar'=>'العاديات','en'=>'Al-Adiyat','slug'=>'al-adiyat','ayahs'=>11,'type'=>'Makkiyah','meaning'=>'The Coursers','benefit'=>'Man is ungrateful to his Lord. He is fierce in love of wealth.'],
  101=>['ar'=>'القارعة','en'=>'Al-Qariah','slug'=>'al-qariah','ayahs'=>11,'type'=>'Makkiyah','meaning'=>'The Calamity','benefit'=>'The Striking Calamity — the Day of Judgement. Scales will be weighed.'],
  102=>['ar'=>'التكاثر','en'=>'At-Takathur','slug'=>'at-takathur','ayahs'=>8,'type'=>'Makkiyah','meaning'=>'The Rivalry in World Increase','benefit'=>'Competition in worldly increase diverts you until you visit graves. Warning against greed.'],
  103=>['ar'=>'العصر','en'=>'Al-Asr','slug'=>'al-asr','ayahs'=>3,'type'=>'Makkiyah','meaning'=>'The Declining Day','benefit'=>'Imam Shafi said if Allah only revealed this surah it would have been sufficient for mankind.'],
  104=>['ar'=>'الهمزة','en'=>'Al-Humazah','slug'=>'al-humazah','ayahs'=>9,'type'=>'Makkiyah','meaning'=>'The Traducer','benefit'=>'Woe to every slanderer and backbiter. Warning against mockery and gossip.'],
  105=>['ar'=>'الفيل','en'=>'Al-Fil','slug'=>'al-fil','ayahs'=>5,'type'=>'Makkiyah','meaning'=>'The Elephant','benefit'=>'Story of Abraha and his army of elephants who came to destroy Kaba. Allah destroyed them.'],
  106=>['ar'=>'قريش','en'=>'Quraysh','slug'=>'quraysh','ayahs'=>4,'type'=>'Makkiyah','meaning'=>'Quraysh','benefit'=>'For the familiarity of Quraysh — their winter and summer journeys. Worship Lord of this House.'],
  107=>['ar'=>'الماعون','en'=>'Al-Maun','slug'=>'al-maun','ayahs'=>7,'type'=>'Makkiyah','meaning'=>'The Small Kindnesses','benefit'=>'He who denies the Day of Judgement also repels the orphan. Social obligations.'],
  108=>['ar'=>'الكوثر','en'=>'Al-Kawthar','slug'=>'al-kawthar','ayahs'=>3,'type'=>'Makkiyah','meaning'=>'The Abundance','benefit'=>'Shortest surah. We gave you Al-Kawthar — river in paradise. Pray and sacrifice.'],
  109=>['ar'=>'الكافرون','en'=>'Al-Kafirun','slug'=>'al-kafirun','ayahs'=>6,'type'=>'Makkiyah','meaning'=>'The Disbelievers','benefit'=>'Equal to quarter of the Quran. Read in Fajr and Maghrib Sunnah prayers. Freedom of faith.'],
  110=>['ar'=>'النصر','en'=>'An-Nasr','slug'=>'an-nasr','ayahs'=>3,'type'=>'Madaniyah','meaning'=>'The Divine Support','benefit'=>'Last surah revealed. Prophet knew his time had come after this. Victory of Islam.'],
  111=>['ar'=>'المسد','en'=>'Al-Masad','slug'=>'al-masad','ayahs'=>5,'type'=>'Makkiyah','meaning'=>'The Palm Fibre','benefit'=>'Abu Lahab and his wife condemned. Miracle — Abu Lahab never accepted Islam as foretold.'],
  112=>['ar'=>'الإخلاص','en'=>'Al-Ikhlas','slug'=>'al-ikhlas','ayahs'=>4,'type'=>'Makkiyah','meaning'=>'Sincerity','benefit'=>'Equal to one third of the Quran. Read 3 times equals complete Quran recitation. Pure tawheed.'],
  113=>['ar'=>'الفلق','en'=>'Al-Falaq','slug'=>'al-falaq','ayahs'=>5,'type'=>'Makkiyah','meaning'=>'The Daybreak','benefit'=>'Muawwidhatain — the two protectors. Read after every prayer. Protection from all evil.'],
  114=>['ar'=>'الناس','en'=>'An-Nas','slug'=>'an-nas','ayahs'=>6,'type'=>'Makkiyah','meaning'=>'Mankind','benefit'=>'Muawwidhatain — the two protectors. Read after every prayer. Protection from whispering shaytan.'],
];

// Top reciters with server URLs
$reciters = [
  ['id'=>'minshawi-murattal','name'=>'Sheikh Al-Minshawi','name_ar'=>'الشيخ المنشاوي','type'=>'Murattal','server'=>'https://server8.mp3quran.net/minsh/','country'=>'Egypt','mosque'=>'','slug'=>'al-minshawi-murattal','featured'=>true],
  ['id'=>'minshawi-mujawwad','name'=>'Sheikh Al-Minshawi','name_ar'=>'الشيخ المنشاوي','type'=>'Mujawwad','server'=>'https://server7.mp3quran.net/minsh-m/','country'=>'Egypt','mosque'=>'','slug'=>'al-minshawi-mujawwad','featured'=>true],
  ['id'=>'sudais-urdu','name'=>'Sudais & Shuraim + Urdu','name_ar'=>'السديس والشريم','type'=>'Urdu Translation','server'=>'https://download.quranicaudio.com/quran/sudais_and_shuraim_urdu/','country'=>'Saudi Arabia','mosque'=>'Masjid Al-Haram, Makkah','slug'=>'sudais-shuraim-urdu','featured'=>false],
  ['id'=>'sudais','name'=>'Abdul Rahman Al-Sudais','name_ar'=>'عبدالرحمن السديس','type'=>'Murattal','server'=>'https://server11.mp3quran.net/sds/','country'=>'Saudi Arabia','mosque'=>'Masjid Al-Haram, Makkah','slug'=>'sudais','featured'=>false],
  ['id'=>'shuraim','name'=>'Saud Al-Shuraim','name_ar'=>'سعود الشريم','type'=>'Murattal','server'=>'https://server7.mp3quran.net/shur/','country'=>'Saudi Arabia','mosque'=>'Masjid Al-Haram, Makkah','slug'=>'al-shuraim','featured'=>false],
  ['id'=>'hudhaifi','name'=>'Ali Al-Hudhaifi','name_ar'=>'علي الحذيفي','type'=>'Murattal','server'=>'https://server6.mp3quran.net/hthfi/','country'=>'Saudi Arabia','mosque'=>'Masjid An-Nabawi, Madinah','slug'=>'al-hudhaifi','featured'=>false],
  ['id'=>'mishary','name'=>'Mishary Rashid Al-Afasy','name_ar'=>'مشاري راشد العفاسي','type'=>'Murattal','server'=>'https://server10.mp3quran.net/Mishary/','country'=>'Kuwait','mosque'=>'','slug'=>'mishary-al-afasy','featured'=>false],
  ['id'=>'basit-murattal','name'=>'Abdul Basit Abdul Samad','name_ar'=>'عبدالباسط عبدالصمد','type'=>'Murattal','server'=>'https://server7.mp3quran.net/basit/','country'=>'Egypt','mosque'=>'','slug'=>'abdul-basit-murattal','featured'=>false],
  ['id'=>'basit-mujawwad','name'=>'Abdul Basit Abdul Samad','name_ar'=>'عبدالباسط عبدالصمد','type'=>'Mujawwad','server'=>'https://server7.mp3quran.net/basit/Almusshaf-Al-Mojawwad/','country'=>'Egypt','mosque'=>'','slug'=>'abdul-basit-mujawwad','featured'=>false],
  ['id'=>'maher','name'=>'Maher Al-Muaiqly','name_ar'=>'ماهر المعيقلي','type'=>'Murattal','server'=>'https://server12.mp3quran.net/maher/','country'=>'Saudi Arabia','mosque'=>'Masjid Al-Haram, Makkah','slug'=>'maher-al-muaiqly','featured'=>false],
  ['id'=>'ghamdi','name'=>'Saad Al-Ghamdi','name_ar'=>'سعد الغامدي','type'=>'Murattal','server'=>'https://server14.mp3quran.net/Ghamdi_40/','country'=>'Saudi Arabia','mosque'=>'','slug'=>'saad-al-ghamdi','featured'=>false],
  ['id'=>'husary','name'=>'Mahmoud Khalil Al-Husary','name_ar'=>'محمود خليل الحصري','type'=>'Murattal','server'=>'https://server13.mp3quran.net/husr/','country'=>'Egypt','mosque'=>'','slug'=>'al-husary','featured'=>false],
  ['id'=>'qatami','name'=>'Nasser Al-Qatami','name_ar'=>'ناصر القطامي','type'=>'Murattal','server'=>'https://server6.mp3quran.net/Nasser_Alqatami/','country'=>'Saudi Arabia','mosque'=>'','slug'=>'nasser-al-qatami','featured'=>false],
  ['id'=>'dossari','name'=>'Yasser Al-Dossari','name_ar'=>'ياسر الدوسري','type'=>'Murattal','server'=>'https://server16.mp3quran.net/Yasser_Al-Dossari/','country'=>'Saudi Arabia','mosque'=>'Masjid Al-Haram, Makkah','slug'=>'yasser-al-dossari','featured'=>false],
  ['id'=>'ajamy','name'=>'Ahmad Al-Ajamy','name_ar'=>'أحمد العجمي','type'=>'Murattal','server'=>'https://server10.mp3quran.net/ajm/','country'=>'Saudi Arabia','mosque'=>'','slug'=>'ahmad-al-ajamy','featured'=>false],
  ['id'=>'juhany','name'=>'Abdullah Al-Juhany','name_ar'=>'عبدالله الجهني','type'=>'Murattal','server'=>'https://server11.mp3quran.net/a_jhn/','country'=>'Saudi Arabia','mosque'=>'Masjid Al-Haram, Makkah','slug'=>'al-juhany','featured'=>false],
  ['id'=>'baleela','name'=>'Bandar Baleela','name_ar'=>'بندر بليلة','type'=>'Murattal','server'=>'https://server11.mp3quran.net/bander/','country'=>'Saudi Arabia','mosque'=>'Masjid Al-Haram, Makkah','slug'=>'bandar-baleela','featured'=>false],
  ['id'=>'salim-bahanan','name'=>'Salim Bahanan','name_ar'=>'سالم بهنان','type'=>'Murattal','server'=>'https://server9.mp3quran.net/slm_bhn/','country'=>'Indonesia','mosque'=>'','slug'=>'salim-bahanan','featured'=>false],
];

function getSurahBySlug($slug, $surahs) {
  foreach ($surahs as $num => $s) {
    if ($s['slug'] === $slug) return array_merge($s, ['number' => $num]);
  }
  return null;
}

function getReciterBySlug($slug, $reciters) {
  foreach ($reciters as $r) {
    if ($r['slug'] === $slug) return $r;
  }
  return null;
}

function padSurah($n) {
  return str_pad($n, 3, '0', STR_PAD_LEFT);
}
?>
